make_packages_yaml improvements
FNALssi/spack-infrastructure pull request #2
Opened 2022-08-19 14:32 UTC by marcmengel

I think this version will meet Chris's specs for using system versions of packages, modulo packages that depend_on libiconv explicitly for example (which should be changed to the virtual iconv dependency, I think).

2022-08-19 15:17 UTC, chissg requested changes

2022-08-19 15:17 UTC, chissg commented on bin/make_packages_yaml
Does `*proto` work with egrep? Seems like it's missing something.

2022-08-19 15:17 UTC, chissg commented on bin/make_packages_yaml
> +force_x86_64="(*proto|asciidoc|autoconf|autogen|automake|binutils|bison|bzip2|cmake|conv|curl|damageproto|davix|diffutils|environment-modules|expat|findutils|fixesproto|flex|font-util|fontconfig|font
See comment above re `*proto`

2022-08-22 17:02 UTC, marcmengel commented on bin/make_packages_yaml
> +force_x86_64="(*proto|asciidoc|autoconf|autogen|automake|binutils|bison|bzip2|cmake|conv|curl|damageproto|davix|diffutils|environment-modules|expat|findutils|fixesproto|flex|font-util|fontconfig|font
Good eyes.  Updated.

2022-08-22 23:04 UTC, chissg approved these changes

2022-08-22 23:05 UTC, merged